<?php
require 'password.php';   // password_verfy()はphp 5.5.0以降の関数のため、バージョンが古くて使えない場合に使用

// セッション開始
session_start();

// ログイン状態チェック
require "functions.php";
loginCheck();

$pdo = connectDB();


?>

<!DOCTYPE html>
<html lang="ja">
<head  prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

<meta charset="UTF-8">
<title>ライブハウス大作戦～有志団体の取り組み～</title>

<link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://eplus.jp/s/page/live/livehouse_support/data/css/style.css">
<script src="https://eplus.jp/s/page/live/js/jquery-3.1.1.min.js"></script>
<script src="https://eplus.jp/s/page/live/js/jquery-migrate-1.4.1.min.js"></script>
<script src="https://eplus.jp/s/page/live/js/jquery.easing.1.3.js"></script>
<script src="https://eplus.jp/s/page/live/js/jquery.colorbox-min.js"></script>
<script src="https://eplus.jp/s/page/live/js/jquery.inview.min.js"></script>
<script src="https://eplus.jp/s/page/live/js/jquery.matchHeight.js"></script>
<script src="https://eplus.jp/s/eplus/js/jquery.cookie.js"></script>
<script src="https://eplus.jp/s/eplus/js/cloud.js"></script>
<script src="https://eplus.jp/s/eplus/js/ui.js"></script>
<script src="https://eplus.jp/s/page/live/livehouse_support/data/js/script.js"></script>


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>
      .youser {
        padding-top:10px;
      }

      .youser01 {
        padding-top:50px;
      }

      .yushi{
        margin-top:30px;
        text-align:center;
      }

    </style>

</head>
<body style="padding-top:3rem;">



  <nav class="navbar navbar-dark bg-dark text-white fixed-top">
      <div class="container youser">
      <!-- ユーザーIDにHTMLタグが含まれても良いようにエスケープする -->
          <strong><p>ようこそ <u><?php echo htmlspecialchars($_SESSION["NAME"], ENT_QUOTES); ?></u> さん</p></strong>  <!-- ユーザー名をechoで表示 -->
          <strong><p>ログアウトは<a href="Logout.php">こちら</a>から</p></strong>
      </div>
  </nav>


    <div class="container text-center mt-5">
        <!-- <div class="text-center bg-dark h-100 pt-4 pb-4 jumbotron jumbotron-extend">
            <p class="display-3 center-block text-white">ライブハウス大作戦</p>
            <p class="display-4 text-white">with コロナ</p>
        </div> -->
        <a href="top.php"><img src="img/top.jpg" alt=""></a>
    </div>
    
    <h2 class="yushi">有志団体の取り組み</h2>


<div class="container youser01">
    
  <article class="article-wrap match-height box-shadow new" id="P-0037"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0037.jpg" alt="" loading="lazy"></div><section><h3>N9S Rock Museum</h3><div class="twitter "><a href="https://twitter.com/N9sRock" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>北九州ライブハウス・スタジオ支援。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>N9S ROCK MUSEUM実行委員会</dd></dl><dl class="support"><dt>支援方法</dt><dd>支援企画に賛同する北九州で活動していた・しているバンド／アーティストが提供した楽曲が保存された「フォルダへのアクセス権」を販売。</dd></dl><p class="price ">500</p><div class="link-text"><a href="https://n9s.net/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.29</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0027"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0027.jpg" alt="" loading="lazy"></div><section><h3>＃キープホープ KEEP HOPE ALIVE</h3><div class="twitter "><a href="https://twitter.com/keephope2020" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>OSAKA RUIDOと京橋Arcのために、仲間の協力を得て寄付金プロジェクトを立ち上げました。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>ひらばやし ともや 他</dd></dl><dl class="support"><dt>支援方法</dt><dd>自分の欲しいものを購入することで、結果として誰かのドリンク代をご馳走することになります。<br>商品の価格は一般的なドリンク代¥600単位。<br>完全にギフトに振り切った「ドリンクギフト券」も用意されている。</dd></dl><p class="price ">600</p><div class="link-text"><a href="https://keephope2020.thebase.in/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.15</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0028"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0028.jpg" alt="" loading="lazy"></div><section><h3>吉祥寺Planet K支援金グッズ</h3><div class="twitter "><a href="https://twitter.com/utataneutouto" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>吉祥寺Planet K支援金グッズ販売中です。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>目黒しおり</dd></dl><dl class="support"><dt>支援方法</dt><dd>グッズを購入すると、手数料を引いた全額が支援金として吉祥寺Planet Kに送られます。</dd></dl><p class="price ">2,350</p><div class="link-text"><a href="https://suzuri.jp/utataneutouto" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.15</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0030"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0030.jpg" alt="" loading="lazy"></div><section><h3>V.A. / come together</h3><div class="twitter "><a href="https://twitter.com/holiday_distro" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>4/16に開催予定だった心斎橋パンゲアとの不定期共催イベント「come together」に出演予定だったバンドを含む、パンゲアと縁の深い11組の楽曲を集めてコンピレーションCD-Rを制作しました。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>HOLIDAY! RECORDS</dd></dl><dl class="support"><dt>支援方法</dt><dd>CDを購入すると、売り上げは本来4/16のイベントが開催予定だった会場の心斎橋パンゲアにすべて寄付されます。</dd></dl><p class="price ">1,000</p><div class="link-text"><a href="https://holiday2014.thebase.in/items/27645375" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.15</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0031"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0031.jpg" alt="" loading="lazy"></div><section><h3>Death Dust Extractor<br>「Extremely Pure Filth Stench Core」<br><span>High Speed Savage Records / HSSR-08</span></h3><div class="twitter "><a href="https://twitter.com/visitor_kotax" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>ライブハウス、スペースがある店の限定発売。<br>売り上げ全てがライブハウスに寄付されライブハウススタッフの在宅ワーク支援を目的としたドネーションCDです。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>High Speed Savage Records</dd></dl><dl class="support"><dt>支援方法</dt><dd>取扱いライブハウスにてCDを購入すると売り上げ全てがライブハウスに寄付されライブハウススタッフの在宅ワーク支援となる。</dd></dl><p class="price ">1,500</p><div class="link-text"><a href="https://twitter.com/visitor_kotax/status/1260097444412395527" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.15</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0032"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0032.jpg" alt="" loading="lazy"></div><section><h3>WRED WORKS</h3><div class="twitter "><a href="https://twitter.com/kouheihama" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>現在コロナウイルス感染拡大防止の休業要請により、無期限の休業をしている札幌のライブハウス【クラブカウンターアクション（KLUB COUNTER ACTION)】を支援するグッズを販売。<br>製作費、経費を除いた売上が全額カウンターアクションへ寄付される。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>カウンターアクションを愛する有志一同(仮)</dd></dl><dl class="support"><dt>支援方法</dt><dd>グッズを購入すると、製作費、経費を除いた売上が全額カウンターアクションへ寄付される。</dd></dl><p class="price off">*金額*</p><div class="link-text"><a href="https://wredworks.thebase.in/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.19</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0033"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0033.jpg" alt="" loading="lazy"></div><section><h3>J-WAVE「#音楽を止めるな」プロジェクト</h3><div class="twitter "><a href="https://twitter.com/jwave813fm" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>J-WAVEでは、新型コロナウイルスの影響で多くのライブイベントが中止となる中、「大好きな音楽を、アーティストを、ライブハウスを応援したい」そのような想いから、「#音楽を止めるな」プロジェクトをスタート。J-WAVEと（株）ビームスから音楽のある豊かな暮らしを提案する、BEAMS RECORDSがコラボレーションし「＃音楽を止めるな」プロジェクトの一環としてライブハウス支援のためのTシャツの受注販売がスタート！J-WAVEにゆかりのあるデザイナー、イラストレーター、写真家などが「＃音楽をとめるな」をテーマにオリジナルイラストやデザインをつくり、BEAMS RECORDSがTシャツを制作。6月7日（日）までONLINEで受注販売を受け付け。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>J-WAVE</dd></dl><dl class="support"><dt>支援方法</dt><dd>Tシャツの売り上げから、製作・販売に掛かる経費を引いたすべての利益は、ライヴプロモーターVINTAGE ROCKを通じて、東京都内を中心としたライヴハウス約40店舗（予定）へ支援。</dd></dl><p class="price ">3,960</p><div class="link-text"><a href="https://shop.eplus.jp/ongakuwotomeruna/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.19</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0034"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0034.jpg" alt="" loading="lazy"></div><section><h3>高知BAY5 SQUARE救済Project</h3><div class="twitter "><a href="https://twitter.com/ROCK_ORANGE" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>高知県にある高知BAY5 SQUAREという、キャパ1200の大ホール、キャパ200の小ホールと、いくつかの練習スタジオを併設する会場を救いたいと思い、グッズを制作して販売する事にしました。</dd></dl><!-- <dl class="organization"><dt>実施主体</dt><dd>*主体名*</dd></dl> --><dl class="support"><dt>支援方法</dt><dd>オリジナルTシャツ、タオルの販売。売上は高知BAY5 SQUAREに還元されます。</dd></dl><p class="price ">1,500</p><div class="link-text"><a href="https://888do.official.ec/categories/2440265" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.19</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0035"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0035.jpg" alt="" loading="lazy"></div><section><h3>富山 音楽施設支援企画</h3><div class="twitter "><a href="https://twitter.com/SpicaToyama" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>富山の音楽関係の施設(スタジオ・ライブハウス)の支援を目的に企画。 新型肺炎ウイルスの影響で、富山の音楽スタジオ・ライブハウスが経営破綻の危機に立たされています。 そこで私たちもサークルとして支援できることをしていこうと思い、このネット販売の窓口を作りました。 売上金は送料や材料費等を抜いた利益は全て、富山のスタジオやライブハウスにお渡しします。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>富山県軽音サークルSpica</dd></dl><dl class="support"><dt>支援方法</dt><dd>ネット販売窓口でのチャリティーグッズの購入 or 寄付</dd></dl><p class="price ">500</p><div class="link-text"><a href="http://spica.toyama-takeout-walk.com/save-toyama-music/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.19</div></article>

  <article class="article-wrap match-height box-shadow new" id="P-0036"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0036.jpg" alt="" loading="lazy"></div><section><h3>ウイルスに負けない！復活へ長期戦になるNAGOYAのライブハウスをみんなで応援しよう！！</h3><div class="twitter off"><a href="https://twitter.com/*Twitter ID*" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>新型コロナウィルスの影響で大きな打撃を受けている名古屋のライブハウス。事態が落ち着いたとしても【ライブハウスの復活】は長期的な闘いになりそうです。 地元のみなさまにご愛顧いただいている「夢チューブ」としてみなさまとそれをできないかと思いプロジェクトを立ち上げました。 参加店さんが用意された様々な商品・サービスをここから購入いただくことで、そのお店の支援ができる仕組みです。名古屋の音楽文化拠点を、地元みんなで応援しませんか。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>夢チューブ「ウイルスに負けない！」実行委員会</dd></dl><dl class="support"><dt>支援方法</dt><dd>名古屋のライブハウス5店舗のへの支援をまとめたプロジェクト。各店舗が用意した返礼品を購入いただくことでそのお店の支援ができます。</dd></dl><p class="price ">1,500</p><div class="link-text"><a href="https://yumetube.en-jine.com/projects/forlh-nagoya" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.19</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0026"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0026.jpg" alt="" loading="lazy"></div><section><h3>HAKONOMI ONLINE</h3><div class="twitter off"><a href="https://twitter.com/*Twitter ID*" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>北九州のライブハウス支援のために立ち上げた企画。</dd></dl><!-- <dl class="organization"><dt>実施主体</dt><dd>下川徹也</dd></dl> --><dl class="support"><dt>支援方法</dt><dd>オンライン飲み会用にあなたの好きなハコの背景画像をダウンロードして応援してください！ 売上は各店舗へ支援金として振り込まれます。</dd></dl><p class="price ">500</p><div class="link-text"><a href="https://stsmile.thebase.in" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.12</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0023"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0023.jpg" alt="" loading="lazy"></div><section><h3>ライブハウス緊急支援<br><span>SAVE THE LIVEHOUSE</span></h3><div class="twitter "><a href="https://twitter.com/311karanotegami" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>これまでたくさんの音や声と共に熱や光をもらってきた全国のライブハウスを恩返しの気持ちも込めて早急に支援したく、ご賛同いただいた上でこの期間に撮影予定でしたバンド、アーティストさんのご協力のもとライブハウス緊急支援オリジナルフォトグッズを制作、販売し、利益全額を全国の支援先ライブハウスへ分配して送金させていただいております。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>石井麻木写真展【3.11からの手紙/音の声】</dd></dl><dl class="support"><dt>支援方法</dt><dd>写真展オンラインショップにてライブハウス緊急支援オリジナルグッズのご購入、ライブハウス緊急支援募金でご支援いただけます。</dd></dl><p class="price ">500</p><div class="link-text"><a href="https://311tegami-onlineshop.stores.jp" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.12</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0024"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0024.jpg" alt="" loading="lazy"></div><section><h3>ライブハウス救済支援コラボレーション<br><span>「無くしてはならない場所~The place you should never lose~」</span></h3><div class="twitter "><a href="https://twitter.com/spanglessweet" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>ライブハウス救済支援＂無くしてはならない場所＂<br>いつまでもそこにあると思っていた”日常”は、割とあっさりと消えて無くなってしまう。<br>第一弾<br>新宿LOFT / 新宿Live Freak / 池袋CHOP / 下北沢CLUB251 / 下北沢MOSAiC / 吉祥寺Planet K / 新代田FEVER / 青山RED SHOES</dd></dl><dl class="organization"><dt>実施主体</dt><dd>SWEET STRANGE SPANGLES</dd></dl><dl class="support"><dt>支援方法</dt><dd>デザインは各ライブハウスを象徴するフォトを使用し、それぞれをSSSのフォーマットに落としこんだものとなっており、この支援企画のキーワードでもある「THE PLACE YOU SHOULD NEVER LOSE」が全て共通にプリントされている。<br>今アイテムに付属するサウンドトラックは、今回のコラボレーションのために急遽製作したSSSオリジナル作品。<br>このコラボレーションから得られる収益は、制作費及び諸経費を差し引き、全て対象ライブハウスに寄付させていただきます。</dd></dl><p class="price ">3,850</p><div class="link-text"><a href="http://ssspangles.com/save/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.12</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0025"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0025.jpg" alt="" loading="lazy"></div><section><h3>みんなでアーティストを応援しよう</h3><div class="twitter "><a href="https://twitter.com/JPMAJAZZ" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>月額定額制で「コンサート行き放題」のサービスを展開している「conpas（運営：オフィス・モデルン）」様が、リアルのコンサート観覧だけでなく、動画視聴についても利益分配を実現するサービス《conpas online》をスタートさせました。日本ポピュラー音楽協会では、アーティストや制作業者がこのサービスを活用して収益を得るためのサポートをさせていただきます。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>一般社団法人日本ポピュラー音楽協会 コンパス・オンライン</dd></dl><dl class="support"><dt>支援方法</dt><dd>動画制作のための協力業者の募集 アーティストが高クオリティな動画を制作するために必要な、会場、撮影、動画編集、演出家、舞台監督、PA、照明について、作品作りにご協力いただける業者様も併せて募集いたします。初期費用は各業者様のご負担になりますが、各業者様にも収益を分配することにより、将来の安定収益につながっていくことを目指します。<br>【募集する業者】※法人・個人は問いません ・会場（ホール、ライブハウス、スタジオ、サロン等） ・撮影 ・動画編集 ・演出家 ・舞台監督 ・PA ・照明</dd></dl><p class="price off"></p><div class="link-text"><a href="http://www.jpma-jazz.or.jp/conpas_online/top.html" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.12</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0018"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0018.jpg" alt="" loading="lazy"></div><section><h3>FIREWORKS PROJECT</h3><div class="twitter "><a href="https://twitter.com/FIREWORKS_P" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>FIREWORKS PROJECTの第1弾としてFIREWORKS T-shirtを制作し販売。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>THE GREENBACK / zanpan</dd></dl><dl class="support"><dt>支援方法</dt><dd>T-shirtを購入すると売上から初期経費を除いた全額が郡山PEAK ACTIONに寄付されます。また、購入特典として「FIREWORKS BOX」カードを同封します。FIREWORKS PROJECTによる様々な在宅コンテンツ(ex.弾き語り動画、限定配信音源、ラジオなど)をアップロードし共有出来るものです。尚こちらは不定期配信となっております。</dd></dl><p class="price ">2,500</p><div class="link-text"><a href="https://fireworksp.base.shop/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.5</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0019"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0019.jpg" alt="" loading="lazy"></div><section><h3>Play For Kumamoto 2020</h3><div class="twitter off"><a href="https://twitter.com/" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>熊本に縁のあるミュージシャン（プロアマ問わず）32組が結集しそれぞれのオリジナル曲を提供したコンピレーションCD（32曲入り2枚組）を制作販売し、その売上全額を熊本県内約20のライブハウス各店に寄付します。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>Play For Kumamoto 2020実行委員会</dd></dl><dl class="support"><dt>支援方法</dt><dd>コンピレーションCDを購入すると全ての売上が熊本県内約20のライブハウスへの支援となります。CD制作費はCDジャケットへの広告協賛と参加アーティストの作品販売売上でまかないます。</dd></dl><p class="price ">1,000</p><div class="link-text"><a href="https://taka495.wixsite.com/pfk2020" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.5</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0020"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0020.jpg" alt="" loading="lazy"></div><section><h3>「KILL'EM ALL FAKIN' METALS」「同 2」復刻およびデジタル配信</h3><div class="twitter "><a href="https://twitter.com/ULTIMATENETWO10" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>Ultimate Networkは1990年代に発売され、長らく絶版だった2枚の国内インディーズヘヴィメタルバンドのオムニバスCD「KILL'EM ALL FAKIN' METALS」（全9曲）「同 2」（全8曲）を復刻、デジタル配信します。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>Ultimate Network</dd></dl><dl class="support"><dt>支援方法</dt><dd>配信サイトでの楽曲購入。<br>配信の売り上げは新型コロナウイルス感染症の影響で経営に苦しんでいるライブハウスへ寄付されます。</dd></dl><p class="price ">2,200</p><div class="link-text"><a href="https://ultimatenetwork.wixsite.com/home" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.5</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0021"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0021.jpg" alt="" loading="lazy"></div><section><h3>Don't Stop Music</h3><div class="twitter "><a href="https://twitter.com/Loud_m_sykes" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>店主デザインのグッズ販売で得られた収益を、クラウドファンディングやその他の方法でお店を存続しようと頑張っておられるライブ空間の支援に充てます。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>大塚 恵</dd></dl><dl class="support"><dt>支援方法</dt><dd>オリジナルグッズを購入すると売上は全て、ライブスペース存続のためのクラウドファンディング等に使用されます。<br>その際のお知らせは、Twitterアカウント等にて報告されます。</dd></dl><p class="price ">2,300</p><div class="link-text"><a href="https://beanscat.base.shop/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.5</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0022"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0022.jpg" alt="" loading="lazy"></div><section><h3>【アカルイツナグミライ】音楽CDプロジェクト</h3><div class="twitter "><a href="https://twitter.com/voxboxstudio" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>コロナ禍により自粛中のクリエイター達と共に作品を制作し、完成したCDをライブハウスやイベント関係に提供させて頂き、その売り上げをもって支援させて頂きます。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>VoxBoxStudio</dd></dl><dl class="support"><dt>支援方法</dt><dd>CAMPFIRE（クラウドファンディングサイト）にてプロジェクト支援が可能です。</dd></dl><p class="price ">1,000</p><div class="link-text"><a href="https://camp-fire.jp/projects/view/259684" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.5</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0001"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0001.jpg" alt="" loading="lazy"></div><section><h3>MUSIC UNITES AGAINST COVID-19</h3><div class="twitter "><a href="https://twitter.com/unites_19" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>新型コロナウイルス（COVID-19）の影響で収益が得られなくなってしまった全国120箇所以上のライブハウスと連携し、支援するプロジェクトMUSIC UNITES AGAINST COVID-19がロックバンド”toe “の発起により2020年4月19日よりスタート</dd></dl><dl class="organization"><dt>実施主体</dt><dd>MUSIC UNITES AGAINST COVID-19 実行委員会</dd></dl><dl class="support"><dt>支援方法</dt><dd>MUSIC UNITES AGAINST COVID-19 フォルダのアクセス権を5種類の価格の中から自分が支援したい金額でダウンロード購入することで、自分が応援したいライブハウスを支援することができます。<br>フォルダの中には「プロジェクトに賛同した約70組のミュージシャンが提供する楽曲データ」が置いてあります。</dd></dl><p class="price ">500</p><div class="link-text"><a href="http://savelivehouse.com" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0002"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0002.jpg" alt="" loading="lazy"></div><section><h3>SUPPORT YOUR LOCAL LIVEHOUSE<span>～チャリティTシャツによるライブハウス支援プロジェクト～</span></h3><div class="twitter off"><a href="https://twitter.com/" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>EX-Cが所属する大阪のSMDcrewが主導する形で、まず大阪のライブハウス3店舗「心斎橋musicbar HOKAGE」、「SOCORE FACTORY」、「心斎橋CLAPPER」よるチャリティTシャツによる支援プロジェクト。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>SMDcrew</dd></dl><dl class="support"><dt>支援方法</dt><dd>ライブハウス支援のチャリティTシャツを販売。<br>諸経費を除いた販売利益の全額がライブハウスに寄付されます。</dd></dl><p class="price ">2,750</p><div class="link-text"><a href="https://www.supportyourlocalcenter.shop/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0003"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0003.jpg" alt="" loading="lazy"></div><section><h3>LIVE FORCE, LIVE HOUSE.</h3><div class="twitter on"><a href="https://twitter.com/LFLHproject" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>LIVE HOUSEを支援するためのリスナーやアーティストが参加できる公正なプラットフォーム作りを目的とし始動。まず第1回の緊急支援としてロック／ポップ系のバンドが主に出演している全国の独立系のライヴハウス約350店を支援対象とし、その後は支援するライヴハウスを追加しながら継続的な活動を行っていきます。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>タワーレコード株式会社 / ならびに協力企業各社</dd></dl><dl class="support"><dt>支援方法</dt><dd>プロジェクトにご賛同いただける支援者の方へピンズ（ピンバッジ）を販売し、そこから得られた利益全額を支援金としてライブハウスへ送金します。支援者は購入の際、支援先の地域やライブハウスを選択できます。地域を選択した場合、各ライブハウスの規模から算出した金額を配分します。</dd></dl><p class="price ">3,000</p><div class="link-text"><a href="http://liveforcelivehouse.com/#/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0004"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0004.jpg" alt="" loading="lazy"></div><section><h3>ライブハウスネバーダイ</h3><div class="twitter off"><a href="https://twitter.com/" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>コロナウイルスの蔓延で、ライブが出来ないライブハウスやクラブ、その他、音を鳴らす場所が危機的状態です。そこで、音を鳴らす場所を絶やしてはならぬ！という気持ち＆このタイミングで恩返しをしよう！という気持ちが合体して出来上がったのが、ライブハウスネバーダイプロジェクトです。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>似てない屋、スドウ図画工作</dd></dl><dl class="support"><dt>支援方法</dt><dd>主催者や支援活動に協賛する人々から募った資金を元に、ステッカーやキーホルダーなどのグッズを作成。作成したグッズを無償でライブハウスなど支援店舗に配布し、各店舗がそれぞれ販売、その販売利益をそのまま収益にしてもらうという取り組みです。</dd></dl><p class="price ">1,000</p><div class="link-text"><a href="https://livehouseneverdieproject.jimdofree.com/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0005"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0005.jpg" alt="" loading="lazy"></div><section><h3>SAVE THE LIVEHOUSE</h3><div class="twitter "><a href="https://twitter.com/savelivehouse" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>また以前と同じようにライブハウスで音楽を楽しめるように。ライブハウスが今を乗り越えられるように。ひとりひとりが直接応援できるプラットフォームを立ち上げました。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>小田翔武 / MASH BROWN / 森下晨弘 / Engineer / 松尾直哉 / 水玉リリー / 須田亘輝 / 株式会社blissCreative / 三木要 / ライブキッズあるある中の人</dd></dl><dl class="support"><dt>支援方法</dt><dd>全国のライブハウスにドリンク代金を事前に支払うことでライブハウスを応援することができるサービスです。</dd></dl><p class="price ">600</p><div class="link-text"><a href="https://savethelivehouse.com/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0006"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0006.jpg" alt="" loading="lazy"></div><section><h3>For Our Live Houses</h3><div class="twitter off"><a href="https://twitter.com/" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>ライブハウスを母体にした会社であり、レーベル、マネジメント業務を兼任するからこそライブハウス・レーベルマネジメント・アーティストのもどかしさ、経営的危機を感じ、この先行きの見えない状況になんとか立ち向かう為、打つ手は無いかと模索する中で立ち上げたプロジェクト。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>TRUST RECORDS / RAD CREATION</dd></dl><dl class="support"><dt>支援方法</dt><dd>コンピレーションアルバム2種・ロゴTシャツ・ステッカーセットを制作し、販売。製造費・配送費等の必要経費を除く全ての売り上げを全国のライブハウスへの支援に充てます。</dd></dl><p class="price ">1,000</p><div class="link-text"><a href="http://radcreation.jp/forourlivehouses/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0007"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0007.jpg" alt="" loading="lazy"></div><section><h3>長野ライブハウス支援プロジェクト</h3><div class="twitter off"><a href="https://twitter.com/" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>プロジェクトは自身達の活動の拠点である長野市内にあるライブハウス、クラブを支援対象に、自分達のライブハウスを守ろうと必死に奮闘するライブハウスの投稿をSNS上で見かけ、そのエネルギーと行動力に感銘を受け、発足したプロジェクト。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>長野ライブハウス支援プロジェクト 代表：上村 悟朗 (MID LOW HIGH HIGH/THE INRUN PUBLICS)</dd></dl><dl class="support"><dt>支援方法</dt><dd>Tシャツの注文、もしくは銀行振込みでの募金により頂いた金額を集計し、SNS等で売上げ金の発表を行い、各ライブハウス、クラブにお渡し致します。</dd></dl><p class="price ">1,500</p><div class="link-text"><a href="http://getover.simdw.com/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0008"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0008.jpg" alt="" loading="lazy"></div><section><h3>OVERCOME THE VIRUS</h3><div class="twitter "><a href="https://twitter.com/lynch_staff" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>直訳すると“ウイルスを克服する”と意味の『OVERCOME THE VIRUS』。この企画は、彼らが書き下ろした新曲を販売し、製作費を差し引いた全利益を“lynch.がこれまでに出演した全国すべてのライブハウス”に分配し寄付するという内容で、メンバーの企画に対する思いが込められたタイトルとなっている。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>lynch.</dd></dl><dl class="support"><dt>支援方法</dt><dd>lynch.がこれまでに出演した全国すべてのライブハウスへ向けた支援となります。<br>このために書き下ろした新曲を販売し、製作費を差し引いた全利益を分配し、寄付となります。</dd></dl><p class="price ">1,000</p><div class="link-text"><a href="https://shadows.lynch.jp/overcomethevirus" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0009"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0009.jpg" alt="" loading="lazy"></div><section><h3>Save Our Place</h3><div class="twitter "><a href="https://twitter.com/ototoy_info" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>ミュージシャンが創った音源をOTOTOYで販売し、その売上をミュージシャンが希望する施設へ届けるという仕組みです。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>ototoy</dd></dl><dl class="support"><dt>支援方法</dt><dd>支援方法① : 音源の配信<br>この企画に賛同していただいたミュージシャン / レーベルの音源をOTOTOYで配信。その売上金(クレジット決済手数料＆著作権使用料を除く)を全額施設に送ります。<br>支援方法② : 無観客ライヴ配信＆ライヴ音源配信<br>営業が制限されてしまっている施設にて、ミュージシャンの無観客ライヴ配信を行い、この無観客ライヴの様子をレコーディングし、後日音源配信を行います。レコーディング費用の実費がまかなわれた時点で、売上金(クレジット決済手数料＆著作権使用料を除く)を全額施設に送ります。</dd></dl><p class="price ">195</p><div class="link-text"><a href="https://ototoy.jp/feature/saveourplace/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0010"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0010.jpg" alt="" loading="lazy"></div><section><h3>LIVE ONE PROJECT</h3><div class="twitter "><a href="https://twitter.com/LIVE_ONE_2020" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>新型コロナウィルスが猛威を振るう今、愛すべき“ライブハウス”を守るために設立したチャリティープロジェクトです。<br>各ライブハウスで購入された商品の収益は、そのライブハウスへ寄付されます。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>LIVE ONE PROJECT</dd></dl><dl class="support"><dt>支援方法</dt><dd>各ライブハウスで購入された商品の収益が、そのライブハウスへ寄付されます。</dd></dl><p class="price ">1,000</p><div class="link-text"><a href="https://liveone.official.ec/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0011"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0011.jpg" alt="" loading="lazy"></div><section><h3>STAY STRONG PROJECT SAVE THE LIVE HOUSE</h3><div class="twitter "><a href="https://twitter.com/HeroesSyndicate" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>現在ライブハウスは新型コロナウィルスの影響で営業停止を余儀なくされ、存続の危機といえる状況になっています。<br>ライブハウスで育ち、ライブハウスと一緒に仕事をしてきた私たちに何かできることはないかと考えた結果、クラウドファンディングで同じ思いの人たちを集い、大好きなライブハウスを支援することが出来ればと、このプロジェクト”STAY STRONG”を立ち上げました。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>運営事務局 / ASIACREATIVE INC. / HEROES SYNDICATE / 株式会社エフネクスト / VISIN HACK LLC.</dd></dl><dl class="support"><dt>支援方法</dt><dd>クラウドファンディングを用いたライブハウスへの支援です。支援額に応じたリターン品有。リターン品はTシャツや、ラバーバンド、ステッカー等。</dd></dl><p class="price ">2,000</p><div class="link-text"><a href="https://stay-strong.asia-creative.jp/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0012"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0012.jpg" alt="" loading="lazy"></div><section><h3>LIVE HOUSE AID in SAPPORO</h3><div class="twitter "><a href="https://twitter.com/LiveHouseAid" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>曲が増え続けるオムニバスアルバムでライブハウスを支援<br>札幌のミュージシャンによるチャリティーアクションです<br>特徴となるのは、オムニバスアルバムに順次楽曲が追加されることです。<br>このアクションに賛同する札幌のミュージシャンが増えれば増えるほど、収録曲数も増えていきます。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>LIVE HOUSE AID</dd></dl><dl class="support"><dt>支援方法</dt><dd>ダウンロード販売型のオムニバスアルバム。決済手数料を除いた売上金の全てをライブハウスへ寄付します。</dd></dl><p class="price ">1,000</p><div class="link-text"><a href="https://www.live-house-aid.hokkaido.jp/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0013"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0013.jpg" alt="" loading="lazy"></div><section><h3>ONGAESHI-音返し</h3><div class="twitter "><a href="https://twitter.com/ongaeshisapporo" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>ONGAESHIは北海道で活動するミュージシャンが集まって特定のライブハウスを支援しようという活動です。<br>持ち寄った音源をウェブで販売し決済手数料以外の売り上げをすべてライブハウスに寄付します。<br>この音源はコンピレーションアルバムとなり、賛同者が増えれば増えるほど、楽曲が追加されていきます。<br>まだ始まったばかりで曲数は少ないですが、ぜひ期待を込めてご購入ください。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>富樫洋介</dd></dl><dl class="support"><dt>支援方法</dt><dd>曲が増え続けるウェブアルバムを販売<br>活動により集まった資金は、決済手数料を除いた全てを上記ライブハウスに均等分配し、運転・設備資金に充当。</dd></dl><p class="price ">500</p><div class="link-text"><a href="https://www.ongaeshi.site/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0014"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0014.jpg" alt="" loading="lazy"></div><section><h3>#LiveHouseNeverDie</h3><div class="twitter "><a href="https://twitter.com/GCR_official" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>サブスク音楽配信収益からの全国のライヴハウスへの自動的な分配を実施する企画です。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>D</dd></dl><dl class="support"><dt>支援方法</dt><dd>Dがこれまで出演した日本各地のライブハウスへ、該当楽曲の配信収益からの10%が自動分配されます。1ダウンロードにつき、またはサブスクリプションでは聴けば聴くほどサポートできます。</dd></dl><p class="price off"></p><div class="link-text"><a href="https://www.d-gcr.com/livehouseneverdie" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0015"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0015.jpg" alt="" loading="lazy"></div><section><h3>LOVE LIVE HOUSE</h3><div class="twitter "><a href="https://twitter.com/LOVELIVEHOUSE" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>Tシャツを購入して寄付したいライブハウスの名前を記入して頂きます。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>遠藤責志(GOOFY’S HOLIDAY) / 矢吹孝之(ex.チェンバロ) / イワタユウシ(AFTER THE NUKES/GOOFY STYLE/ex.NUKEY PIKES) / 小林ハジメ(スペースカンフーマン/THREEMASONRY) / 江口亮(STEREO FABRICATION OF YOUTH)</dd></dl><dl class="support"><dt>支援方法</dt><dd>Tシャツを購入して寄付したいライブハウスを提示すると製作費などを除いた売り上げは全て、そのライブハウスの収益になります。</dd></dl><p class="price ">2,000</p><div class="link-text"><a href="https://shop.lovelivehouse.com/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0016"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0016.jpg" alt="" loading="lazy"></div><section><h3>Moon Romantic　Kazuhiro Bessho feat. Kan Sano</h3><div class="twitter "><a href="https://twitter.com/kazzbe" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>「Kan Sanoのトラックを使って、１曲作りました。bandcampで100円で売ってます。追加の寄付も歓迎。そして、bandcampの収益は未来永劫全額、僕が一番身近でお世話になっているライブハウス、月見ル君想フに寄付します。」</dd></dl><dl class="organization"><dt>実施主体</dt><dd>別所和洋</dd></dl><dl class="support"><dt>支援方法</dt><dd>bandcampで売っているデジタルトラックを購入すると、ライブハウス・月見ル君想フに寄付されます。</dd></dl><p class="price ">100</p><div class="link-text"><a href="https://kazuhirobessho.bandcamp.com/track/moon-romantic" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

  <article class="article-wrap match-height box-shadow" id="P-0017"><div class="image"><img src="https://eplus.jp/s/page/live/livehouse_support/images/volunteer/P-0017.jpg" alt="" loading="lazy"></div><section><h3>MORNING GLORY Project</h3><div class="twitter "><a href="https://twitter.com/myeahns" target="twitter"><img src="https://eplus.jp/s/page/live/livehouse_support/data/images/icon_twitter.svg" alt=""></a></div><dl class="outline"><dt>概要</dt><dd>Tシャツの売り上げをmyeahnsとゆかりのある新宿LOFT/新宿red cloth/下北沢BASEMENTBAR/名古屋・今池HUCK FINN/大阪・心斎橋Pangeaに寄付。</dd></dl><dl class="organization"><dt>実施主体</dt><dd>myeahns</dd></dl><dl class="support"><dt>支援方法</dt><dd>Tシャツを購入すると、経費をのぞいた金額がmyeahnsとゆかりのあるライブハウスに寄付されます。</dd></dl><p class="price ">2,500</p><div class="link-text"><a href="http://site-2427500-8424-4159.mystrikingly.com/" target="_blank">詳細はこちら</a></div></section><div class="date">2020.5.1</div></article>

      </div>
    </div>
  </section>

<!-- <div class="link-button"><a href="post.html">掲載希望はこちら</a></div> -->
</div>
<div class="page_top"><a href="#top" class="square">ページTOP</a></div>
</div>

</body>
</html>